### ISSUE TITLE
Implement unlink UX

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-link#10]
A followup of #2.

----

There are 2 possible approaches to unlinking. They could even exist along each other, it's not a big deal:

## Through link panel

Pros

* It does not clutter the panel but gives the user a chance to change their minds.
* Some people might look for unlink in the same UI where they linked in the first place.
* It does not clutter the toolbar.

Cons

* Requires 2 clicks to unlink (open link panel, click the button).

![image](https://cloud.githubusercontent.com/assets/1099479/17898215/37050d0e-6957-11e6-8279-c93ee26116eb.png)

## Unlink button in the toolbar

Pros

* A single click to unlink.
* v4–compatible, people could expect something similar.

Cons

* Clutters the toolbar. However, this could be resolved by creating a drop–button in the toolbar.
  * Drop–button makes unlink 2 clicks away again :)

![image](https://cloud.githubusercontent.com/assets/1099479/17898249/5723082a-6957-11e6-9575-4512b3491cb0.png)

**Comment by scofalik** [comment]
I think that unlink feature is rarely used, I guess mostly after someone pasted some contents and then want to remove links. I think that if someone wants to remove a link they want to remove also the text of the link.

So, having this in mind, I'd go with two toolbar buttons AND unlink button in linking tooltip:
* people are used to separate unlink button, I always look for it if I need this functionallity,
* it's faster in a scenario that is in my opinion more common that is removing links from pasted content (I still don't belive that people write some text, link some words and then decide to remove those links after all),
* it does not clutter toolbar that much but is easy to remove if someone wants to -- we still have this functionallity in linking tooltip.

**Comment by oleq** [comment]
@scofalik You just confirmed that my ideas are right :)

As for detailed unlink mechanism, I'm for adapting the default mechanism from v4:

* Unlink selected text only, even if there's more to unlink.
* Retain the selection after unlink.

![image](https://cloud.githubusercontent.com/assets/1099479/17923438/72908b7c-69e4-11e6-8d68-431fe9ff66b9.png)

**Comment by scofalik** [comment]
Yes I did, I just didn't want to go with "+1" :P

**Comment by RyszardB** [comment]
my proposal.. change the button link to unlink
![screen shot 2016-08-24 at 11 49 56](https://cloud.githubusercontent.com/assets/17498197/17926419/435846c6-69f1-11e6-8fe3-5e363176a1ce.png)

**Comment by scofalik** [comment]
Then you can't change the link href.

**Comment by oleq** [comment]
Yes, buttons can change dynamically in the toolbar to reflect changes in the content. However only if
* The button which is to be replaced is irrelevant in the current context. Which is not true in case of the link button, because it's still useful to edit existing link, if selection is anchored to one.
* There's still an easy way to access the feature, if necessary. Like keyboard shortcut or some other place (like menu) which offers access to the feature.

Anyway, editing link by placing a selection inside of it with mouse will become another issue I'm preparing at this moment.

**Comment by RyszardB** [comment]
hmm.. only one button.. check this out:
![u2](https://cloud.githubusercontent.com/assets/17498197/17929608/cf59b410-6a01-11e6-8e0b-2de7c441bb06.png)

**Comment by oleq** [comment]
@RyszardB Not sure if I got it right. You idea is basically to get rid of unlink button in the toolbar and that's it?

**Comment by Reinmar** [comment]
With just one button it will be really confusing that you need to click the link button and then the unlink button in the tooltip to unlink. Very bad discoverability and as you can see here https://twitter.com/reinmarpl/status/766384770284740608 it's VERY dangerous :D.

So, IMO we must have some unlink button visible when you have selection in a link. It can be a toolbar button or a button floating over a link. I believe that the second option wasn't yet mentioned. We could have a small balloon over link (and later over images, tables, etc.) with the most useful options. In case of a link it will be edit link and unlink buttons.

**Comment by oleq** [comment]
@Reinmar I created a [separate issue](https://github.com/ckeditor/ckeditor5-link/issues/17) for it so let's discuss it there and find out what is possible and what is not.

**Comment by oleq** [comment]
Anyway, whatever the solution we finally agree upon, I expect this issue to produce **at least** a basic (v4–like) unlink button in the toolbar in this iteration. This is the minimum goal for iteration3.

**Comment by oleq** [comment]
Closed by https://github.com/ckeditor/ckeditor5-link/pull/19.
