### ISSUE TITLE
Page is scrolled when the balloon is closed (ESC, unlink)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#100]
![apr-10-2017 12-20-14](https://cloud.githubusercontent.com/assets/156149/24857314/22b8d8da-1de8-11e7-8cb8-f15d9bebaafe.gif)

Make sure to have focus in the input.

**Comment by Reinmar** [comment]
Reproduced on Chrome.

**Comment by oskarwrobel** [comment]
Related: https://github.com/ckeditor/ckeditor5-engine/issues/707

**Comment by Reinmar** [comment]
It's the same issue actually. Let's see where the fix will need to land.

**Comment by oleq** [comment]
It turned out the easiest way to fix the issue is to enhance editing view's `DomConverter`, see https://github.com/ckeditor/ckeditor5-engine/issues/951.

**Comment by Reinmar** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-engine/issues/951.
