### ISSUE TITLE
Editor blurs when CTRL+K pressed too soon after selection is done

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-link#125]
![editor-blurs-when-ctrl_k-pressed-too-soon](https://cloud.githubusercontent.com/assets/1099479/26450082/f8b19022-4155-11e7-9bd4-1ff489a32a9b.gif)

The issue is not reproducible if there's more time before making a selection and pressing the keystroke.

**Comment by oleq** [comment]
This is odd but I can't reproduce the issue anymore 🤔

**Comment by oleq** [comment]
Got it again. The trick is to use the touchpad instead of the mouse. I'm able to reproduce it in MacOS. I suppose there could be some kind of a (system?) timeout after the gesture is finished and before the actual `selectionchange` event is fired.

**Comment by Mgsy** [comment]
I'm not able to reproduce this bug.
