### ISSUE TITLE
Link balloon disappears while dragging a selection with blured URL input

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-link#126]
## Steps to reproduce
1. Create a new link.
2. Click it to open a link balloon.
3. Make sure that URL input is blured.
4. Try to select "Link URL" label.

## Current result
Link balloon disappears when you start to drag a selection.

## Expected result
Link balloon should remain visible.

## Note
Link balloon won't disappear only if you try to drag a selection with focused URL input.

## Other informations
OS: Windows 10, Ubuntu 16.04
Release: 0.10.0

**Comment by oleq** [comment]
I'm unable to reproduce this issue
![kapture 2017-05-30 at 9 37 23](https://cloud.githubusercontent.com/assets/1099479/26572827/a652cd18-451b-11e7-9ba6-1a8c8356781c.gif)

**Comment by Mgsy** [comment]
Actually, bug is reproducable only if you save your link. So try this way - type some text, select whole word, convert it into a link, open link balloon again and try to make a selection mentioned in this issue.

**Comment by oleq** [comment]
Thanks, now I got it. The issue occurs only when there's no focus moved to the panel and the "Link URL" text is selected (or just clicked anywhere but at the input).

**Comment by oleq** [comment]
This issue will be closed in https://github.com/ckeditor/ckeditor5-ui/issues/243.

**Comment by szymonkups** [comment]
> This issue will be closed in https://github.com/ckeditor/ckeditor5-ui/issues/243.

Issue closed - @Mgsy can you check it now and possibli close this ticket?

**Comment by Mgsy** [comment]
Thanks, @szymonkups. Actually, I can still reproduce this bug on Chrome and Opera. On Safari, Firefox and Edge everything works fine.

**Comment by oleq** [comment]
Checked in Chrome and looks like it works just fine. Have you pulled the latest branches @Mgsy?

![kapture 2017-06-14 at 11 17 44](https://user-images.githubusercontent.com/1099479/27125006-2fa76cc6-50f3-11e7-8758-558abd97949f.gif)

**Comment by Mgsy** [comment]
Hmm, @oleq, that's strange. I pulled everything, I also done a rebuild of classic editor and checked on manual tests. Still doesn't work for me on Chrome.

**Comment by Mgsy** [comment]
After today's update I checked it once again and issue doesn't occur anymore. I'm not sure, why last time I was able to reproduce it, but now everything is okay. 

It's fixed, so I'm closing this ticket.
