### ISSUE TITLE
CTRL+K listener should check if the command is enabled before opening the balloon

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-link#128]
## Steps to reproduce
1. Open editor's sample.
2. Create a new line below the image.
3. Double-click on a new line to select some blank space.
4. Press CTRL + K.

## Current result
Link balloon shows up and allows user to create a link, but after saving nothing happens. 

## Notes
- On Safari after performing step 4, link balloon shows up in the top-left corner of a browser. 
- Toolbar's behavior is correct, because styling and link buttons are disabled.

## GIF
![bug](https://cloud.githubusercontent.com/assets/20988892/26782714/3f1fd8d2-49f5-11e7-9ce6-ac48b4274a7c.gif)

## Other information
OS: Windows 10, MacOS X, Ubuntu 16.04
Browser: Chrome, Safari, Firefox
Release: 0.10.0

**Comment by oleq** [comment]
Yes, <kbd>Ctrl</kbd>+<kbd>K</kbd> listener does not check whether the command is enabled or not and just calls `_showPanel`. This must be fixed.

As for Safari, there's an issue for that already https://github.com/ckeditor/ckeditor5-ui/issues/126.

**Comment by oskarwrobel** [comment]
This is related to https://github.com/ckeditor/ckeditor5/issues/340#issuecomment-250485108.

**Comment by oleq** [comment]
I suppose we should somehow bind keystroke listeners and commands in such situations. It's not a big deal though at this moment.
