### ISSUE TITLE
Balloon opened with CTRL + K shouldn't show up after closing it with mouse click

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-link#130]
## Steps to reproduce
1. Open a balloon with <kbd>CTRL</kbd> + <kbd>K</kbd>.
2. Click on some paragraph.

## Current result
Balloon shows up for a very short time in a place where you have clicked.

## GIF
![bug](https://user-images.githubusercontent.com/20988892/27033107-2926a3e8-4f78-11e7-91c3-fd9e66c5c8c9.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Firefox, Edge, Opera
Release: 0.10.0

**Comment by oleq** [comment]
Probably an issue with `ContextualBalloon`.

**Comment by Reinmar** [comment]
Hm... adding to iteration 11. It may be a quick fix and I've some feeling that it may be related to https://github.com/ckeditor/ckeditor5-link/issues/129.

**Comment by oleq** [comment]
It probably has been fixed along with https://github.com/ckeditor/ckeditor5-ui/issues/281. Can you confirm this @Mgsy?

**Comment by Mgsy** [comment]
> It probably has been fixed along with ckeditor/ckeditor5-ui#281. Can you confirm this @Mgsy?

Yes, this bug doesn't occur anymore. Thanks, I'm closing this issue.
