### ISSUE TITLE
LinkBalloonPanel should be displayed in read-only mode when Link/Unlink commands are disabled

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-link#135]
Balloon should be displayed but modifying the link element should be not possible.
Input should be read-only, Unlink and Submit buttons should be disabled.

**Comment by oleq** [comment]
IMO you should not be able to open the panel when the command is disabled. See https://github.com/ckeditor/ckeditor5-link/pull/133.

**Comment by oskarwrobel** [comment]
You should by clicking on the link element. This is needed by https://github.com/ckeditor/ckeditor5/issues/492.
