### ISSUE TITLE
The link balloon doesn't show up when clicking for the first time

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#150]
![sep-05-2017 09-47-46](https://user-images.githubusercontent.com/156149/30050609-5ee2ef66-921f-11e7-9368-bb5a3b4aab5a.gif)

I think that the trigger is having a refreshed editor. Blurring the editor doesn't cause the issue.

**Comment by oleq** [comment]
I can't reproduce it.

**Comment by Mgsy** [comment]
@Reinmar, are you using Safari? If so, the real bug is that the caret moves to the beginning of the editor on first focus. I think I reported this issue some time ago.

It works fine on other browsers.

**Comment by Reinmar** [comment]
I'm using Chrome. And I can't reproduce this anymore...

But I could in the past (I remember I noticed it before) and I could when recording this. So there's some race perhaps. Perhaps it's a close race in Chrome (so it happens randomly) and in Safari some other option wins (hence the caret moves somewhere)...

Try opening the console. It helped in my case and I'm again able to reproduce this. Try a couple of times.

**Comment by Mgsy** [comment]
Okay, I managed to reproduce this issue on Chrome. But it seems that bug occurs only on OS X, because I'm not able to reproduce it on Windows.

**Comment by Reinmar** [comment]
OK, then let's just keep this ticket open and wait :)

**Comment by oleq** [comment]
Are you guys using Chrome "Version 60.0.3112.113 (Official Build) (64-bit)"? Still no success reproducing this issue on Mac.

**Comment by Mgsy** [comment]
> Version 60.0.3112.113 (Official Build) (64-bit)

Yes, I'm using exactly this version.

**Comment by Reinmar** [comment]
Me too. Since this issue is more reproducible with console opened I think it may be related to performance. Run `npm i` somewhere in bg and try again :D

**Comment by Reinmar** [comment]
Not reproducible for me anymore. @Mgsy?

**Comment by Mgsy** [comment]
> Not reproducible for me anymore. @Mgsy?

After few refreshes, I was able to reproduce it in https://ckeditor5.github.io.

**Comment by oleq** [comment]
Has [that one](https://github.com/ckeditor/ckeditor5-link/issues/180) fixed this issue too?

**Comment by Mgsy** [comment]
>Has that one fixed this issue too?

I'm not able to reproduce it on the latest master, so I guess it's fixed.
