### ISSUE TITLE
[FF] Browser steals selection on CLTR+K

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-link#153]
### Steps to reproduce

1. Open a sample, for example: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/balloon-editor.html
2. Select some text.
3. Press <kbd>Ctrl</kbd> + <kbd>K</kbd> to open link balloon.

### Expected result

Field in balloon is focused.

### Current result

Browser steals selection and focuses in search bar.

### Notes

I think this is because we cannot cancel default event.

**Comment by Reinmar** [comment]
Strange that it doesn't work. I don't recall problems with handling this keystroke.

**Comment by fredck** [comment]
> I think this is because we cannot cancel default event.

This works well in GDocs and Medium, so it should be doable to control these keys.

**Comment by Reinmar** [comment]
If we'll have anyone able to look into this, we may squeeze it into it12. @ma2ciek, could you check it?

**Comment by scofalik** [comment]
Of course, we already had similar issue with <kbd>Tab</kbd> that is used in List feature.

**Comment by Reinmar** [comment]
Wasn't the issue with lists different? Wasn't it caused by two features not being able to decide which should handle <kbd>Tab</kbd>?
