### ISSUE TITLE
Link balloon doesn't close after setData() if the selection was collapsed

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-link#166]
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Open the console.
3. Put the caret somewhere in the editor.
4. Open the link balloon.
5. Paste it to the console: `editor.setData('<p>test</p>')`.
6. Press <kbd>Enter</kbd>.

## Expected result
The link balloon isn't visible.

## Current result
The link balloon moves to the beginning of the document.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/35673849-f5327886-0742-11e8-9453-c8e9c491bc96.gif)

## Notes
It doesn't occur if we make this operation on non-collapsed selection or on existing link.

## Other information
OS: All platforms
Browser: All browsers
Release: Latest master

**Comment by oleq** [comment]
It could be strongly related to https://github.com/ckeditor/ckeditor5-engine/issues/1267. 

cc @pjasiun, @scofalik.

**Comment by oleq** [comment]
I cannot reproduce it after https://github.com/ckeditor/ckeditor5-link/pull/165 because a lot has changed in the link's logic in this PR so let's see what comes out of it.

**Comment by Mgsy** [comment]
This bug isn't reproducible anymore after https://github.com/ckeditor/ckeditor5-link/pull/165.
