### ISSUE TITLE
Shouldn't link button be on when caret is inside a link?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#173]
Right now the toolbar doesn't react to moving the caret which I suddenly found a bit odd. Bold, italic, block quote, etc. – they all are highlighted, but the link isn't.

This gets more important now when we add https://github.com/ckeditor/ckeditor5-link/issues/72.

**Comment by Reinmar** [comment]
cc @oleq @dkonopka @jodator

**Comment by jodator** [comment]
From my POV it could be highlighted as you described. It does look odd to me. Also for the two-step carent movement would be additionally good to highlight the link button as the caret goes into link.

**Comment by oleq** [comment]
If the button is "on" in this situation, then it supposed to be a 2-state. 

What would happen if a user clicked the button in such situation? My common sense tells me the button goes off but... then what? Unlink?

And if it does not go off, how to tell the user that it was pushed (even further?) to open the link UI?

**Comment by Reinmar** [comment]
> What would happen if a user clicked the button in such situation? My common sense tells me the button goes off but... then what? Unlink?

Can't it simply focus the URL input (if it wasn't focused)? Sounds ok to me, but I'd need to see this live.

**Comment by oleq** [comment]
ATM the first step is the link actions view so there's no input there to focus. We could switch to the link editing view in such situation but I'm not sure this is the expected UX for the users.

**Comment by Reinmar** [comment]
I've been playing today with the link highlight and two-step caret movement and I find this really missing that nothing changes in the toolbar when the highlight appears. The button switching on would make the signal that you enter a link clearer.

Are you sure, @oleq, that it's a big deal that the button would be on?

**Comment by oleq** [comment]
> Are you sure, @oleq, that it's a big deal that the button would be on?

Google Docs keeps it off (but they **always** display the balloon)

![image](https://user-images.githubusercontent.com/1099479/37143951-f2751a3c-22bc-11e8-99ba-d2c3b8a0c0db.png)

I also checked other WYSIWYG editors. Some follow this approach and some don't. 

If this a such a big deal, then OK, let's have it on and see if this feels _right_.

**Comment by Reinmar** [comment]
Google Docs thinks that a link is underlined blue text :D So...

**Comment by Reinmar** [comment]
I've just reported https://github.com/ckeditor/ckeditor5-highlight/issues/16 which might be an answer to my question:

> Are you sure, @oleq, that it's a big deal that the button would be on?

When the button is on I was expecting that pressing it will have an action. I'm not sure whether moving focus to link editing balloon will be enough. Perhaps it will, but we certainly have to provide that action.

**Comment by Reinmar** [comment]
Are you typing with a link or not?

![image](https://user-images.githubusercontent.com/156149/41527358-3203e622-72e7-11e8-8d2e-16058553756f.png)

Which also made me think that 

```css
	--ck-color-link-selected-background: 						hsl(201, 100%, 96%);
```

Should use a `hsla()` so to look better on non-white backgrounds. cc @dkonopka
