### ISSUE TITLE
<a> AttributeElement priority

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-link#174]
I wonder what should be the priority of `view.AttributeElement`s created by link feature. Right now it is just `5`, because "5 is less than 10 (the default priority)".

Shouldn't it be that `<a>` in DOM is always topmost non-container element? Isn't it that we never want `<a>` to be broken? For example:

`<span class="marker"><a href="foo.html">Fo</a></span><a href="foo.html">obar</a>`.

This is wrong most of the time. Is it wrong all the time?

If so, my proposal is to set `priority` to `Number.NEGATIVE_INFINITY`.

**Comment by jodator** [comment]
Maybe there will be some elements that requires higher priority? If so maybe `priority` should be set to `Number.NEGATIVE_INFINITY - 10`.

:trollface: a bit but negative infinity is a bit to extreme and leaves no room for error.

**Comment by scofalik** [comment]
You posted :trollface: but TBH I wanted to propose the same. Thankfully I wasn't sleeping on math lessons and soon realized that `Number.NEGATIVE_INFINITY === Number.NEGATIVE_INFINITY + 10` :P.

**Comment by Reinmar** [comment]
I don't think we're going to change this. Let's see if people somehow stumble upon this, first.

**Comment by scofalik** [comment]
I disagree with closing this ticket.
