### ISSUE TITLE
Do we need validation for href value?

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-link#18]
Do we want to prevent users from entering invalid `href` value?
What is invalid href value?

There is a lot of valid options:
`#anchor`, `http://example.com?foo=bar`, `mailto:mail@example.com`, `tel:123456789`. Even empty string seems to be valid href value.

**Comment by oskarwrobel** [comment]
I think that right now when LinkPanel is a general panel for any kind of link (not dedicated for url or email etc) validation may be unnecessary.

**Comment by Reinmar** [comment]
I don't think that we need or should validate it by default. However, an ability to easily plug a validator (from a different feature) would make a lot of sense. Then, in use cases where a developer wants to limit users, there will be a non-hacky option.

**Comment by oleq** [comment]
I think it's related to https://github.com/ckeditor/ckeditor5-link/issues/4.

**Comment by oskarwrobel** [comment]
Ok, so I won't implement any validation in basic version of link feature and we will back to this in #4 ticket.
