### ISSUE TITLE
Allow setting link's target attribute (allow opening links in new tabs)

### ISSUE THREAD

**Issue by itelmenko** [ckeditor/ckeditor5-link#186]
## Original ticket description

> Hello!
>
> There are not ability to select target of link in ckeditor5 . 
>
> Please, add it

## Feedback needed

Please read this discussion starting from [this comment](https://github.com/ckeditor/ckeditor5-link/issues/186#issuecomment-452392660) and leave your feedback (by adding a reaction) in [this comment](https://github.com/ckeditor/ckeditor5-link/issues/186#issuecomment-452608537).

**Comment by oleq** [comment]
Hi, @itelmenko. We consider implementing this feature in the future. There is no strong ETA, though.

All we can do at this moment is add the `target` attribute to all links in the editor view and output data by overriding the default downcast converter.

```js
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import {
	downcastAttributeToElement
} from '@ckeditor/ckeditor5-engine/src/conversion/downcast-converters';

const linkElementSymbol = Symbol( 'linkElement' );
const linkTarget = '_blank';

class MyLinkTargetPlugin extends Plugin {
	init() {
		const editor = this.editor;

		// Override the default downcast converter provided by the LinkEditing class.
		editor.conversion.for( 'downcast' )
			.add( downcastAttributeToElement( {
				model: 'linkHref',
				view: createLinkElement,
				priority: 'high'
			} ) );
	}
}

function createLinkElement( href, writer ) {
	const linkElement = writer.createAttributeElement( 'a', {
		href,
		target: linkTarget
	}, { priority: 5 } );

	writer.setCustomProperty( linkElementSymbol, true, linkElement );

	return linkElement;
}
```

Then you can simply use the plugin in editing initialization

```js
ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ ..., MyLinkTargetPlugin ]
	} );
```

**Comment by oleq** [comment]
BTW: We're working on some [conversion improvements](https://github.com/ckeditor/ckeditor5-engine/issues/1348) to make the code shorter and to avoid overriding the default converter (which is not safe in the long run).

**Comment by itelmenko** [comment]
Thanks @oleq for snippet!
But I can not try it because I have not 
```
 '@ckeditor/ckeditor5-core/src/plugin';
 '@ckeditor/ckeditor5-engine/src/conversion/downcast-converters';
```
How can I install it?

Also it is interesting issue:
When I run `npm run watch` it's OK.
But if I run `npm run production` I get:
```/js/backend/message/editor.1a1e6e866c5e902a4770.js from UglifyJs
Unexpected character '`' [./~/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5,6550][/js/backend/message/editor.1a1e6e866c5e902a4770.js:93,6517]```

I use Laravel 5.6 (where laravel-mix use webpack 2.7.0)

Is it webpack issue or ckeditor?

**Comment by oleq** [comment]
> Thanks @oleq for snippet!
> But I can not try it because I have not
> 
>  '@ckeditor/ckeditor5-core/src/plugin';
>  '@ckeditor/ckeditor5-engine/src/conversion/downcast-converters';
> How can I install it?

Check out this guide https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/development/installing-plugins.html

> Also it is interesting issue:
> When I run npm run watch it's OK.
> But if I run npm run production I get:
> 
> /js/backend/message/editor.1a1e6e866c5e902a4770.js from UglifyJs
> Unexpected character '`' [./~/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5,6550][/js/backend/message/editor.1a1e6e866c5e902a4770.js:93,6517]
> I use Laravel 5.6 (where laravel-mix use webpack 2.7.0)
> 
> Is it webpack issue or ckeditor?

We also noticed certain issues with UglifyJs in https://github.com/ckeditor/ckeditor5-dev/issues/371 (Webpack 4.x uses it by default). ATM I'd rather recommend you to use `babel-minify-webpack-plugin` which works just fine.

**Comment by ssougnez** [comment]
Hi,

I just found this topic while wondering how come it was not possible to add target to a link.

@oleq, you asked what kind of UI was expected for this. Why not a simple drop down with the posssible values (https://www.w3schools.com/tags/att_a_target.asp). 

I guess the first implementation of this feature might not include framename as almost no one uses frame anymore anyway.

This seems to me like a mandatory feature and when you see the awesome job you did for tables, it’s really a shame that links miss such a basic functionality.

I really hope someone will find the time to implement this feature.

**Comment by imkane** [comment]
I'm surprised that not every single user of CKEditor would like the option to open links in a new tab. Otherwise, every link in your app will break out of the app. Isn't this like a mandatory feature?

**Comment by Reinmar** [comment]
> I'm surprised that not every single user of CKEditor would like the option to open links in a new tab. Otherwise, every link in your app will break out of the app. Isn't this like a mandatory feature?

It depends.

* links within the website does not need to (and often should not have) this attribute,
* links to external websites or out of an SPA should have this attribute.

CKEditor 5 can't decide automatically what should be the behaviour. Therefore, there are two options:

* it could be configurable which links (based on URL) are produced with `target=blank` by CKEditor 5,
* `target=blank` could be added automatically by the backend (when outputting the content to the target page).
* ~users can decide~ (from UX perspective it's a rather bad option)

The former is something that we can implement, of course, and perhaps will. We just don't have this on the roadmap yet.

The second option is what many CMS does. It's actually the best. The content output from CKEditor 5 is treated as abstract data. This data is stored in HTML format, but that's just a format. But from the abstraction perspective, links have no such property as how they should be opened – that's not to be defined by the data itself. That's to be defined by the system which renders that content to the end users – i.e. your backend systems.

**Comment by imkane** [comment]
A follow up question ...

This feature was available in CKEditor 4. Why was it removed from v5? Or was it just somehow decided that it wasn't important to implement early on?

**Comment by Reinmar** [comment]
## Our opinion

> How could the system know whether the user wants the link to open in a new tab or not?

The question is – how can the user know that? Usually, normal users don't understand and/or care about such things. Plus, a system can do things consistently, based on predefined rules. Users won't do that. If you want all external links to be opened in a new tab (which is what most people want), you can automate this. As I see it this is the most common scenario and therefore that'd be our first step.

However, I understand that in some specific scenarios where these really are users who make the final decision it needs to be possible to control this attribute via the balloon. That's also a feasible extension, but I'd consider this a second step.

> This feature was available in CKEditor 4. Why was it removed from v5? Or was it just somehow decided that it wasn't important to implement early on?

A bit of both. When implementing CKEditor 5 we had to review the existing features and rethink most of them. CKEditor 4 (and CKEditor 3 and FCKeditor) have a long history of adding WYSIWYG features in a way which works for developers and for building websites, but makes less sense for normal users and from content semantics perspective. CKEditor 4 started turning into the WYSIWYM direction around 2013 and CKEditor 5 just follows that. It's a rich-text editor which allows WYSIWYM editing. The behaviour of links is just not part of content semantics and a technical detail which most users wouldn't normally care. Also, this happens to be in line with other modern editors – Quill, Prosemirror or Slate don't let you set the target as well. Markdown doesn't allow this too.

But I said "a bit of both" because I don't say we would never implement it. It's just something that's nice to have (because in some cases it may be necessary), but wasn't there in the roadmap to 1.0.0.

## Feedback needed

What I wrote above is how we think about it. We may be wrong regarding the priorities so, please vote:

* Add ❤️ if you want an abiity to configure CKEditor 5 which links should be output with `target=_blank` and which not. This would be an automatic behaviour, based on link URL. For instance, you could configure CKEditor 5 that all external links are produced with `target=_blank`.
* Add 🎉 if you want a "Open link in new tab" checkbox in the link balloon.

**Before voting** please read this discussion starting from [this comment](https://github.com/ckeditor/ckeditor5-link/issues/186#issuecomment-452392660) up to this one.

**Comment by imkane** [comment]
It's sorta funny you talk about other modern editors not having the link target feature, but you fail to talk about BY FAR the most common one out there ... the one that runs 30% of websites ... WordPress. If they ever got rid of link target ability there'd be riots lol.

For anyone like myself using CKEditor in a SaaS, setting an _optional_ link target is **absolutely crucial.** I can think of numerous other applications where it would be as well. I'm still quite surprised you haven't received many, many more complaints about this.

You can probably tell that I of course voted for the "open link in a new tab" checkbox :)

**Comment by FFohlin** [comment]
@Reinmar To have our backend parse every text and rewrite the a elements is not an option.

**Comment by daveh02** [comment]
@Reinmar When is the voting closed and the outcome presented ? When can we expect the checkbox option ?🙂

**Comment by Reinmar** [comment]
Note to ourselves: Let's update https://stackoverflow.com/questions/49366292/ckeditor-5-links-set-default-target-for-links-or-edit-target once we get this.

**Comment by Reinmar** [comment]
> @Reinmar When is the voting closed and the outcome presented ? When can we expect the checkbox option ?🙂

Well :trollface: I saw many votes on the checkbox option coming from Swedes (hello from Poland, BTW ;) and newly registered users on the very first day after I asked the question. Normalizing the results with that in mind I'd say it's a draw. Most importantly though, both options got votes, which means that  both are worth being implemented. When? IDK yet.

**Comment by Reinmar** [comment]
> @Reinmar To have our backend parse every text and rewrite the a elements is not an option.

Can I ask why?

**Comment by FFohlin** [comment]
> > @Reinmar To have our backend parse every text and rewrite the a elements is not an option.
> 
> Can I ask why?

Sure. We are using blank for different reasons. We are not able to use the url to determine if the blank should be used or not. internal or external links (or other url parts) does not help us.
Futhermore we try to have the wysiwyg editor to show the result as clearly as possible, and we would have to both parse the html backend, and build some script to tell the content editors what they can expect in result. Very often they do not see the result on the site when creating the article. 

In our company this became a problem for quite a few. And some of them even registered here maybe :)

Keep up the good work, we really like changes made between 4 and 5!
(I think more table functionality is on the wish list for our editors soon)

**Comment by ssougnez** [comment]
As everyone seems to give use case for this, I'll add mine. We are using umbraco cms to allow content managers to create the content. However the site has some dynamic component made in angularjs. The problem is then that some sentence displayed by these content needs to be translated (text like "no result found". So I use the balloon editor to enable content manager to edit these label on the fly.

In this label, managers can add link but the must be able to specify how the link opens...

**Comment by mlewand** [comment]
We actually would like to provide means to solve both approaches:

* **automatic** - as it is very convenient to use if you're able to define the rules properly
* **manual** - it provides end user with maximal control of the feature

While thinking about API, this feature can actually be generalized and not limited to assigning targets only. Other use cases include `a[download]`, `a[rel]`, `a[ping]` attributes. For instance one might want to force download for all links that are contained in, say, `/uploads/` directory.

So the common feature sounds more like link decorators.

```js
config.link.decorator = [ 
	{
		// Mode could be either manual or automatic.
		mode: 'automatic',
		callback: function( url ) {
			// This should be a more precise regexp.
			return url.startswith( 'https://' );
		},
		// This is a set of attribute applied to the link in view.
		attributes: {
			rel: 'noopener noreferrer',
			target: '_blank'
		}
	},
	{
		mode: 'manual',
		label: 'Force download', // Label for the checkbox.

		attributes: {
			download: 'download'
		}
	},
	{
		mode: 'automatic',
		callback: function( url ) {
			return url.includes( '/gallery/' ) && url.endswith( '.png' );
		},
		attributes: {
			class: 'lightbox'
		}
	}
];
```

The config to manually handle `a[target=_blank]` would be the following:

```js
config.link.decorator = [ {
	mode: 'manual',
	label: 'Open in a new window',

	attributes: {
		target: '_blank',
		manualTarget: true
	}
} ];
```

**Comment by Reinmar** [comment]
>  It sounds better for me to make this an opt-in.
>
> In that case our documentation should contain listings for both solutions.

👍 for opt-in and samples of as many solutions as possible.

Other notes:

* `config.link.decorator` -> `config.link.decorators` (cause there are many)
* `'Open in a new window'` needs to be translatable – we should document it clearly that if you'll use this string precisely, then it will be translated to the chosen language.
* Finally, I think that it should be "Open link in new tab", just like the tooltip for the link URL in the link balloon.

**Comment by msamsel** [comment]
@mlewand, @Reinmar 
I'm wondering how specific cases should be covered with **manual decorators** and ranged selection.

As I can see there isn't displayed any UI for range selection on links, even if those are entirely inside single link. However it's possible to execute command on such range, and behaviour in such cases really depends from selection range.

Should this feature support somehow ranged selection, or be available exclusively for collapsed one and link creation from toolbar?

**Comment by Reinmar** [comment]
It should do exactly the same thing which the link command does. It must be 1:1 synced with it. In fact, I think that perhaps we should extend the link command here to ensure it always applies all the attributes.

**Comment by lasfin** [comment]
@oleq 
Could you show how updated code after [conversion improvements](https://github.com/ckeditor/ckeditor5-engine/issues/1348) should looks like?

```
init() {
        const editor = this.editor;
        const conversion = editor.conversion;

        // Override the default downcast converter provided by the LinkEditing class.
        conversion.for( 'downcast' ).add(
            editor.conversion.attributeToElement( {
                model: 'linkHref', // tried also use Link as a model (from @ckeditor/ckeditor5-link)
                view: createLinkElement,
                priority: 'high'
            } )
        );
    }

```

**Comment by mlewand** [comment]
This feature just got merged to the `master` branch 🎉 You'll be able to set `[target=_blank]` (and any other attributes) just by changing the configuration using link decorators feature.

Basic configuration should looks something like that:

```js
ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ Link, Typing, Paragraph, Clipboard, Undo, Enter ],
		toolbar: [ 'link', 'undo', 'redo' ],
		link: {
			decorators: {
				isExternal: {
					mode: 'manual',
					label: 'Open in a new tab',
					attributes: {
						target: '_blank'
					}
				}
			}
		}
	} );
```

More info will be available in the docs.

Sample screencast:
![screencast showing open in a new tab switch added to the link panel](https://user-images.githubusercontent.com/5353898/60184736-dddef100-9828-11e9-8339-336cd179cf40.gif)

**Comment by yura-tovt** [comment]
Hi @mlewand. Thanks for implementing this feature. But it seems that upcast conversion is missing.

**Comment by msamsel** [comment]
> Hi @mlewand. Thanks for implementing this feature. But it seems that upcast conversion for additional attributes is missing.

I'm on it. As I talk with @Reinmar it's important issue. It's reported here as well #233.

**Comment by mlewand** [comment]
Thanks for catching that! We're working hard to include it in the upcoming release, keep an eye on #233 for quickest update.

**Comment by Nivekul** [comment]
I followed this [tutorial](https://ckeditor.com/docs/ckeditor5/latest/features/link.html) and added the `link: { addTargetToExternalLinks: true }` configuration. But it did absolutely nothing, is there something I'm missing?

I'm using CKEditor5 Classic Build in Vue, version 12.3.1.

**Comment by oleq** [comment]
@Nivekul What data (editor content) did you use?

**Comment by Nivekul** [comment]
> @Nivekul What data (editor content) did you use?

I'm not sure what is the data (editor content), but the following is how I setup the editor
```vue
<ckeditor v-model="article" class="editor" :editor="editor" :config="editorConfig"
          @focus="editorFocused=true" @input="handleEdit"></ckeditor>
```
```js
article: '',
editor: ClassicEditor,
editorConfig: {
    toolbar: {
        items: [
            'Heading', '|',
            'bold', 'italic',
            'link', 'blockQuote',
            'ImageUpload',
            'MediaEmbed',
        ]
    },
    link: {
        addTargetToExternalLinks: true,
    },
    image: {
        toolbar: ['imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight', '|', 'imageTextAlternative'],
        styles: ['full', 'alignLeft', 'alignRight'],
    },
    placeholder: 'Start writing your article here ...',
    extraPlugins: [(editor) => this.uploadAdapter(editor, this)],
},
```

**Comment by oleq** [comment]
So what happens to links starting with "https://" or "http://" or "//" in your content?

**Comment by Nivekul** [comment]
@oleq I see, it works now! Thanks!
