### ISSUE TITLE
Create a custom link button

### ISSUE THREAD

**Issue by joachimdoerr** [ckeditor/ckeditor5-link#195]
How i can create a custom link button for a CMS implementation?

**Comment by Reinmar** [comment]
What do you mean? What do you want it to do?

cc @oleq

**Comment by joachimdoerr** [comment]
Hello @Reinmar, for the cms [redaxo](https://github.com/redaxo/redaxo) i want to create a extension that provide the ckeditor5. The button that I need to add must be call a cms dialog like the screenshot:
![bildschirmfoto 2018-05-04 um 19 51 00](https://user-images.githubusercontent.com/1191549/39643506-433740ea-4fd5-11e8-8074-fc1a59559791.png)
* On click to the Button "Interner Link" a popup will be open and you can chose a Site:
![bildschirmfoto 2018-05-04 um 19 51 14](https://user-images.githubusercontent.com/1191549/39643632-a91bce8a-4fd5-11e8-88f7-9bfddf6d8799.png)
* On click to a site in the linklist the popup close automatically and write the cms link into the link input field:
![bildschirmfoto 2018-05-04 um 19 51 20](https://user-images.githubusercontent.com/1191549/39643666-c8252862-4fd5-11e8-9ce0-2240b0778ef9.png)

**Comment by oleq** [comment]
Would you like to use the existing UI (see below) or build a new one for that?

![image](https://user-images.githubusercontent.com/1099479/39752601-3b4321f8-52bc-11e8-9418-da6e138a3d84.png)

**Comment by oleq** [comment]
You can write a simple plugin to add a button to the existing UI. Check out https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/installing-plugins.html to learn how to extend existing editor build, create own editor builds, etc.

![image](https://user-images.githubusercontent.com/1099479/39813992-f8d24d6c-5392-11e8-987a-c273b27bfd12.png)


```js
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import LinkUI from '@ckeditor/ckeditor5-link/src/linkui';

class InternalLink extends Plugin {
	init() {
		const editor = this.editor;
		const linkUI = editor.plugins.get( LinkUI );

		this.linkFormView = linkUI.formView;
		this.button = this._createButton();

		this.linkFormView.once( 'render', () => {
			// Render button's tamplate.
			this.button.render();

			// Register the button under the link form view, it will handle its destruction.
			this.linkFormView.registerChild( this.button );

			// Inject the element into DOM.
			this.linkFormView.element.insertBefore( this.button.element, this.linkFormView.saveButtonView.element );
		} );
	}

	_createButton() {
		const editor = this.editor;
		const button = new ButtonView( this.locale );
		const linkCommand = editor.commands.get( 'link' );

		button.set( {
			label: 'Internal link',
			withText: true,
			tooltip: true
		} );

		// Probably this button should be also disabled when the link command is disabled.
		// Try setting editor.isReadOnly = true to see it in action.
		button.bind( 'isEnabled' ).to( linkCommand );

		button.on( 'execute', () => {
			// Do something (like open the popup), then update the link URL field's value.
			// The line below will be probably executed inside some callback.
			this.linkFormView.urlInputView.value = 'http://some.internal.link';
		} );

		return button;
	}
}
```

**Comment by joachimdoerr** [comment]
@oleq thanks for your example!
* I try to use that and create for it this repository https://github.com/basecondition/ckeditor5-rexlink and publish it as a npm package. 
* Than is add the package as `devDependencies`, add it to the build.config as `plugins`, and add it to the `src/ckeditor.js`.
```
	plugins: [ ....
		'ckeditor5-rexlink/src/rexlink'
	],
```
```
...
import RexlinkPlugin from 'ckeditor5-rexlink/src/rexlink';
...
ClassicEditor.build = {
	plugins: [
		RexlinkPlugin
	],
```
* Than I try to build the editor `npm run build`. That works but I get this warning: 
```
WARNING in ./src/ckeditor.js
59:2-15 "export 'default' (imported as 'RexlinkPlugin') was not found in 'ckeditor5-rexlink/src/rexlink'
 @ ./src/ckeditor.js
```

What is wrong?

**Comment by jodator** [comment]
Probably missing `export` keyword before `class` here:

https://github.com/basecondition/ckeditor5-rexlink/blob/master/src/rexlink.js#L8

**Comment by joachimdoerr** [comment]
@jodator thanks! Now it works. @oleq your example works absolutely perfect! Thanks a lot!

**Comment by joachimdoerr** [comment]
I have still one question about that. I want add the button optional. As options like `alignment` 
```
options['alignment'] = [ 'left', 'right', 'center', 'justify' ];
```
Also: 
```
options['rexlink'] = [ 'internal', 'media' ];
```
How i can modify the plugin to ensure it?

**Comment by oleq** [comment]
Your plugin should define a config option in plugin's constructor, e.g.

```js
constructor( editor ) {
	super( editor );

	editor.config.define( 'link.rexlink', [ 'internal', 'media' ] );
}
```

then in the `init()` you can read the config's value and make the buttons conditional:

```js
const rexlinkConfig = editor.config.get( 'link.rexlink' );

if ( something about rexlinkConfig ) {
	// create buttons or not
}
```



```js
ClassicEditor
	.create( ...., {
		link: {
			rexlink: [ 'foo' ]
		}
	} )
	.then( editor => {
		window.editor = editor;
	} )
	.catch( err => {
		console.error( err );
	} );
```

**Comment by joachimdoerr** [comment]
Thanks @oleq thats work perfekt!

* Now i add 2 svg icons for the media and the internal button. I think that looks good 
![bildschirmfoto 2018-05-10 um 14 48 27](https://user-images.githubusercontent.com/1191549/39870334-406f7da6-5461-11e8-98c4-05c3ec6d58ef.png)

* The next point that i see is the link text problem. When i dont mark any words in the text and add a link the editor will be add the link with the link as text - that is ok for domain links but for internal links that look stupid
![bildschirmfoto 2018-05-10 um 14 59 23](https://user-images.githubusercontent.com/1191549/39870761-c9b04cac-5462-11e8-9d16-812dd64404ae.png)

* The internal link widget gives the internal link site title. is it possible that the editor write an other text as the link target text in this case?

* For this i want to use the `linktext` : https://github.com/basecondition/ckeditor5-rexlink/blob/master/src/rexlink.js#L75

**Comment by oleq** [comment]
@joachimdoerr Check out https://github.com/ckeditor/ckeditor5-link/issues/73 and https://github.com/ckeditor/ckeditor5-link/issues/15. 

You can try listening to `LinkFormView#submit` event, which is fired when the user clicks the save ("tick") button. Then, if you discover that the link is internal and the current selection is collapsed (nothing is selected), you can [insert a corresponding text](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/faq.html#where-are-the-editorinserthtml-and-editorinserttext-methods-how-to-insert-some-content). It could work.

**Comment by joachimdoerr** [comment]
@oleq thanks for the event idee. For now I crate this solution that works for me 
```
        button.on( 'execute', () => {
            // Do something (like open the popup), then update the link URL field's value.

            var linkMap = openLinkMap('', '&clang=1');
            const urlInputView = this.linkFormView.urlInputView;
            const thatLinkFormView = this.linkFormView.element;
    
            $(linkMap).on('rex:selectLink', function (event, linkurl, linktext) {
                event.preventDefault();
                linkMap.close();
    
                // The line below will be probably executed inside some callback.
                urlInputView.value = linkurl;
    
                $(thatLinkFormView).submit(function(){
                    var regex = '>' + linkurl + '<',
                        matches = editor.getData().match(regex);
    
                    if (matches) {
                        var result = editor.getData().replace(regex, '>' + linktext + '<');
                        editor.setData(result);
                    }
                });
            });

        } );
```

The next step is the image integration. I want to use the redaxo mediamanager to add images. In which repository can I open a issue about that?

**Comment by oleq** [comment]
If I were you, I'd experiment with https://github.com/ckeditor/ckeditor5-link/issues/195#issuecomment-388057470. What you did in the last snippet could fail if one decided to change the text of the link later on and then insert the same URL somewhere else because (if I got it correctly) it blindly seeks certain `<a>` and replaces their text. It will override existing texts upon successive insertions of the same link.

> The next step is the image integration. I want to use the redaxo mediamanager to add images. In which repository can I open a issue about that?

Check out https://docs.ckeditor.com/ckeditor5/latest/api/adapter-ckfinder.html
