### ISSUE TITLE
Link panel should close when clicking body of the web page

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-link#20]
Link panel should close when clicking outside of it and outside of the editor (i.e. in the body of the webpage). Otherwise people will leave orphan panels open and, as the content/geometry of the page changes, the panels will lose their anchor and float weirdly without making any sense.

Related issue: https://github.com/ckeditor/ckeditor5-link/issues/3.

**Comment by fredck** [comment]
Shouldn't this be relative to the selection?
 *  If I click inside the editor and the selection goes outside the link, the panel hides. Same logic works when creating a link (always closing the balloon then).
 * If the editor loses focus, the panel hides.

**Comment by oleq** [comment]
Yes, @fredck, the panel should be in sync with the selection in the editor. And it works in the current implementation. 

But this issue is about what happens when the user clicks somewhere out of the editor (a different input in the form), some page navigation, whatever, really.

**Comment by Reinmar** [comment]
Clicking somewhere on a page means blurring the editor UI. So a more general way of thinking about it would be related to focus manager.

**Comment by oskarwrobel** [comment]
Clicking outside of the panel and outside of the editor should close the panel and not restore editor focus (e.g. someone click on input outside the editor and want to write something)? But clicking on some editor UI element (e.g. toolbar) should close the panel and restore the editor focus?

**Comment by Reinmar** [comment]
Yes.

**Comment by fredck** [comment]
Basically, the panel should not care about focus in such case. The click itself will handle this... when outside it'll cause the editor to blur... when in the editor UI, will cause the focus to be restored.

**Comment by oskarwrobel** [comment]
It is not so easy, because focus manager has information that panel is open and when panel will be closed FM will try to restore focus on editor.

**Comment by oleq** [comment]
FM is not supposed to manipulate the focus. It just registers some UI elements and provides an API to tell "hey, this div, which is somewhere in DOM belongs to the editor". And that's it. v4 works like that. 

Other components of the editor will then use that API and check whether the focus is still in the editor or not, instead of checking focus on editable. This way editable can be blurred, but FM knows that some fancy panel not belonging to editable which has been just clicked is considered a part of editor (it has been registered) so it tells other components (like floating toolbar) that the focus is still there. It's a synthetic focus.

**Comment by oskarwrobel** [comment]
Yep, you are right guys.

**Comment by Reinmar** [comment]
Fixed by #34.
