### ISSUE TITLE
Link panel should be closed when the browser window is resized

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-link#22]
ATM the panel has `position:absolute` relative to the `<body>`. So when the browser window is being resized, the panel loses the anchor context and floats  detached from the editor, which looks odd, like

![image](https://cloud.githubusercontent.com/assets/1099479/18385344/4aacd738-7690-11e6-8629-ed305ce177b6.png)

**Comment by Reinmar** [comment]
IMO, a better solution would be to reposition the panel. That would save you from crying when you tried to use it on a mobile browser and rotated your device to type a link. But since mobile UX is yet to be defined, and we may end up with a separate UI implementation, then perhaps it's not an issue.

**Comment by oleq** [comment]
Yes, repositioning is also an option. We can go with it now, TBH.

As a followup, I'd check then what if the balloon had some smart CSS transition for `top/left` properties. It could slide and follow the content, which might actually look quite good. 

BTW: It's also broken in https://cksource.com/accessibility-checker/demo.html :D

**Comment by oleq** [comment]
We should address it ASAP, it's annoying ;-)

![oct-13-2016 16-58-47](https://cloud.githubusercontent.com/assets/1099479/19354315/8af14f04-9166-11e6-9468-2831324e89e0.gif)

**Comment by Reinmar** [comment]
You serious? :D When are you resizing windows in real life use cases? You said that A11y checker has the same problem and... somehow no one complains :P.

**Comment by fredck** [comment]
It happened to me as well and I "closed my eyes" to not see it as a bug :D

I would be happy to see it fixed... if no reposition, at least disappearing.

**Comment by oleq** [comment]
> You said that A11y checker has the same problem and... somehow no one complains :P.

I complained but no one listened. It's my nemesis just like https://github.com/ckeditor/ckeditor5-ui/issues/2 is yours, @Reinmar ;-)

**Comment by oskarwrobel** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-ui/pull/196
