### ISSUE TITLE
The link panel is not displayed when selection spans the entire link element

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-link#23]
1. Focus editable.
2. Select the link, i.e. like this

![image](https://cloud.githubusercontent.com/assets/1099479/18385594/e05daf5e-7691-11e6-8b83-f1bfb632e682.png)

Expected: Link panel appears for the selected link.

Actual: Nothing happens.

**Comment by oleq** [comment]
Alright. In F2F talk we decided with @oskarwrobel that this behaviour is valid and even expected in some sort of way. However, as @oskarwrobel pointed out, the panel should appear on double click on the link. I think it makes sense. It is something v4 users may be used to.

**Comment by oleq** [comment]
OTOH, double clicking might be reserved for other editing tasks, like the user wants to select some text in the link and bold it.

**Comment by fredck** [comment]
Hum... I still have the sensation that the panel should appear in such case. After all, the panel doesn't block other features to be executed over the selection, right?

**Comment by oleq** [comment]
@fredck ATM I'm thinking about slightly different approach to opening the panel with mouse/keyboard because the problem is bigger, in fact. I'll submit it as another issue ASAP.

**Comment by oleq** [comment]
@fredck I described the problem in https://github.com/ckeditor/ckeditor5-link/issues/26 (RFC!). If we drop "focus stealing" behaviour for mouse interactions, then we could always display the panel – for collapsed, non–collapsed, partial, and full selection in editable.

**Comment by Reinmar** [comment]
I see that we agreed on #26 (I'm reviewing it now and it works great), so I assume that this issue is confirmed and we can open the balloon when entire link is selected (I agree with @fredck that this is expected behaviour).

**Comment by Reinmar** [comment]
Can we have this fixed? It may sometimes (#116) be really confusing.
