### ISSUE TITLE
[Docs] It's really hard to read snippets which have vertical scrollbar

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#236]
![image](https://user-images.githubusercontent.com/156149/60426987-10586780-9bf6-11e9-8d89-80ba2674e231.png)

Especially, if you're supposed to see how they update live.

**Comment by oleq** [comment]
You can get 

![image](https://user-images.githubusercontent.com/1099479/60443341-52e06b00-9c1b-11e9-8c8c-e82f8042fe43.png)

by adding

```html
<style>
	#output-link-decorators {
		overflow: hidden;
		white-space: normal;
		word-break: break-all;
	}
</style>
```

I'm not sure this is easier to read, though. 

Anyway, if we decided to go this way, this should become a class you can set on `<code>` in

```html
<pre class="highlight">
	<code class="html hljs" id="output-link-decorators"></code>
</pre>
```

so we can re-use it in onther guides. 

WDYT?

cc @dkonopka @msamsel

**Comment by msamsel** [comment]
It's better for sure.
I wonder if Umberto could expose HTML beautifier. It's used for CKE4 examples but on server-side.

However, embedding beautifier would increase the `app.js` size for about 10KB (https://github.com/beautify-web/js-beautify).

**Comment by Reinmar** [comment]
Definitely better when it's wrapped. 

I don't think it requires any more work at the moment. And you can indeed make it a more generic selector.
