### ISSUE TITLE
Focus manager integration for the link UI

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-link#3]
ATM v5 has no focus manager. 

The problem is that if the Link UI will bring external panel, which then will contain inputs, which when focused will steal the focus of the editable. It's not a big deal in the engine because the selection is in the model and can be easily retained. The real issues lies in the sticky toolbar that must remain visible and which is bound to editable `isFocused` attribute. 

For instance, if an input in a balloon panel was focused in such situation

![image](https://cloud.githubusercontent.com/assets/1099479/17734834/014b01b4-647f-11e6-8076-254ad851688e.png)

the toolbar would be lost because the actual DOM focus is moved from editable to the input.

The solution is a focusmanager registry that, like in v4, would inform the editor that focus remains in the UI and propagate that information to focus–dependent features like sticky toolbars, floating panels, tooltips, etc.

Should FM become a separate package? How to implement it properly? Where to discuss it?

**Comment by Reinmar** [comment]
Sounds to me like a `FocusManager` in ckeditor5-core. It will need to be exposed in the `Editor` instances and when a feature which claims to be the editor part and may get focus should register itself. I think that we can copy CKE4's solution in this case. The devil will be in the details of course, e.g. whether we still need that evil timeout, how specific components should register themselves, etc. But this we should discuss in a separate ticket.

**Comment by oleq** [comment]
Closed by https://github.com/ckeditor/ckeditor5-link/issues/36.
