### ISSUE TITLE
Use smarter balloon positioning to avoid placing it off the viewport

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-link#33]
![image](https://cloud.githubusercontent.com/assets/1099479/18633579/4b3f13f6-7e7d-11e6-8de9-2914c333dd2b.png)

**Comment by oleq** [comment]
Before checking [this](https://github.com/ckeditor/ckeditor5-ui-default/blob/t/77/src/balloonpanel/balloonpanelview.js#L192), the algorithm should check if `rects[ rectPos ]` fits in the viewport first.

**Comment by oskarwrobel** [comment]
I haven't seen this issue and I've created the same in https://github.com/ckeditor/ckeditor5-ui-default/issues/76. Fix will be in `ckeditor5-ui-default` so I'm closing this one.
