### ISSUE TITLE
[FF] Problems displaying the LinkBalloonPanel

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-link#37]
First of all, the panel is not displayed when the selection lands in a link. Then, if clicked Link in the toolbar, the panel is attached to nowhere and off the viewport.

It feels like there's some problem with the discovery of the link under the selection.

![](https://cloud.githubusercontent.com/assets/1099479/18746164/2a887512-80c6-11e6-84b1-e1997be60961.png)

**Comment by oleq** [comment]
Related issue https://github.com/ckeditor/ckeditor5/issues/201.

**Comment by oskarwrobel** [comment]
After enabling `dom.select_events.enabled` flag (see https://github.com/ckeditor/ckeditor5-engine/issues/407) and merging https://github.com/ckeditor/ckeditor5-ui-default/pull/84 everything should be fine:

![link ff](https://cloud.githubusercontent.com/assets/1057056/18906127/8cd09930-8566-11e6-88a2-227dd914bf53.gif)

**Comment by oleq** [comment]
This is odd, but let's wait for FF team to sort this out.

**Comment by Reinmar** [comment]
This issue should be fixed in ckeditor/ckeditor5-utils#153.
