### ISSUE TITLE
Form rendering and validation

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-link#4]
Link UI requires at least one input to work properly. However, it might be extended with additional fields, which then must become a part of a unified data model, which must be 

1. rendered,
2. validated,
3. (optionally) cross–validated,
4. synchronised with inputs, checkboxes, etc.

What is the right architecture do do this? Should it become a separate Form UI component? How complex should it become? How to avoid v4–style dialog mess?

Link is the first feature to bring this kind of mechanisms to the editor.

**Comment by Reinmar** [comment]
I'm for creating now a simple input component which can display a validation error if that's what we need for the link feature. Or even for using HTML5 form validators.

I wouldn't try to design now more complex solutions. We neither know whether we need a more complex solution nor how and what kind of forms will be created. CKEditor 4's system is helpful if you don't want to work with HTML and you're creating simple forms, but has huge limitations if you want to do anything more. And it's huuuge. That's not the way for CKEditor 5.

A solution that may be fully sufficient could be a set of simple to use form fields with some, but not obligatory validation options that can be triggered automatically and checked on submit. All that doesn't have to automated. E.g. on submit it may be up to you whether you validate or not and which fields. Also, it may be up to you whether you block that, where do you display errors, etc. So I rather see this as a set of utils.

**Comment by oskarwrobel** [comment]
Related to: https://github.com/ckeditor/ckeditor5-ui-default/issues/54

**Comment by Reinmar** [comment]
https://github.com/ckeditor/ckeditor5-ui-default/issues/54 contains an interesting discussion **whether we should validate the link URL or not**. This ticket is about how to do that, so merging them may be confusing if both aspects will trigger longer discussions.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5-link/pull/19.
