### ISSUE TITLE
[FF ES5] LinkBalloonPanel failed test.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-link#47]
On FF49, with selection change event, on ES5 build, one test is failing:

https://github.com/ckeditor/ckeditor5-link/blob/master/tests/ui/linkballoonpanel.js#L85-L96

It says that it fails because done callback has not been called, but in fact `executeSpy.calledOnce` is also not equal to true.

**Comment by oskarwrobel** [comment]
Strange, works fine on `macOS 10.12`

![image](https://cloud.githubusercontent.com/assets/1057056/19035349/513891a0-8969-11e6-9486-52592bd404e8.png)

But test should be refactored. should use `element.dispatchEvent( new Event( 'click' ) )` instead of `element.click()`.

**Comment by oskarwrobel** [comment]
Sorry I've checked wrong test case.

[This one](http://localhost:1030/build/modules/amd/tests/link/ui/linkballoonpanel#saveButton%20should%20fire%20model%23executeLink%20event%20on%20DOM%20click%20event) doesn't work.
