### ISSUE TITLE
Wrong position of balloon panel when used in an empty block

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-link#49]
Balloon panel is located in top-left corner when used on empty list element. There are other issues reported with similar effect, so this might be a duplicate.

![output](https://cloud.githubusercontent.com/assets/2396463/19064721/644f5bec-8a0f-11e6-8706-76634503da1d.gif)

**Comment by oskarwrobel** [comment]
Probably good fix for this will solve [that issue](https://github.com/ckeditor/ckeditor5-link/issues/46) too.

@Reinmar hint: https://github.com/ckeditor/ckeditor5-link/issues/46

Here is an example of [manual test](https://github.com/ckeditor/ckeditor5-ui-default/blob/febd886c52580f6c7e245c80bc745b929b3c0f14/tests/tickets/90/1.js).

**Comment by ssougnez** [comment]
Hi, I'm also experiencing this issue with the version 0.5.1 of "ckeditor5-link". The positioning is correct when some text is selected. I notice that if I remove the inline styles

```
top: 15px;
left: -30px;
```

From the `div` displaying the balloon, it is correctly positioned.

Cheers

**Comment by oleq** [comment]
This issue should be fixed in https://github.com/ckeditor/ckeditor5-utils/issues/153.
