### ISSUE TITLE
Cannot link a text

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#74]
1. Select text.
2. Click the link button.
3. Type URL.
4. Press enter or the "save" button.

Nothing happens.

The other issue is that when opening the link balloon again it contain the previous text.

If such bugs weren't noticed it means that this package lacks integration tests, so they must be added when fixing this issue.

**Comment by oleq** [comment]
Feels like https://github.com/ckeditor/ckeditor5-link/issues/65.

**Comment by Reinmar** [comment]
I know, I remember this one. But this is a lesson not to accept PRs which have no ticket test.

**Comment by oleq** [comment]
From https://github.com/ckeditor/ckeditor5-ui/issues/103:

> Not related to this PR, but why is native click prevented only when button is not enabled?

That's why! ;-)

https://github.com/ckeditor/ckeditor5-ui-default/pull/120/commits/50fb6b847390d0073fa92f2ca663aa7bb0244068 should be reverted.

**Comment by Reinmar** [comment]
LOL :D. So, of course, it deserves a comment there and automated test for that.

But in such a case I understand why our tests might not catch it. Firing DOM events is not something that we'd like to extensively do in automated tests (I don't even know whether it will trigger submit). OTOH, if we rely on that submit behaviour, it'd be good to have at least one test for that, so you can check whether firing a custom DOM click event triggers submit too.

**Comment by oleq** [comment]
I mean, the test should remain but with different assertions. Plus we need a real test for `LinkFormView`<->`Link` interaction in DOM because AFAIR we just fire `submit` event on `LFV` and this will pass even if there's no "Submit" button in the form.

**Comment by Reinmar** [comment]
Reverted in https://github.com/ckeditor/ckeditor5-ui-default/commit/3b6200ce58ef73cf09f9fc9c68afa43f29ebc772. Still deserves tests in both packages.
