### ISSUE TITLE
You shouldn't be able to link an image (just yet)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#85]
The link feature should be disabled when an image is selected. Most likely some state check is missing.

In the future, we'll add the possibility to link images, but so far we don't have converters for that.

Alternatively, instead of fixing the state check now, we can add a converter allowing linking images. But the state check needs to be fixed at some point anyway.

**Comment by Reinmar** [comment]
To clarify why images can't be linked yet – the problem here is that so far we support linking text, so we can convert text attribute to a `<a>` element.

With images we need to convert an element attribute to an `<a>` element. Also, the `<a>` itself should land inside the `<figure>` element:

```html
<figure class="image">
  <a href="..."><img src="..." alt="..."></a>
  <figcaption>Caption.</figcaption>
</figure>
```

**Comment by Reinmar** [comment]
Please see the discussion in https://github.com/ckeditor/ckeditor5-link/pull/132#issuecomment-315057592.

The quick fix was too brutal. A slightly better fix would be to change this behaviour in `Schema#checkAttributeInSelection()` but that means affecting also bold and italic and we decided no to disable them on images (at least not yet). See https://github.com/ckeditor/ckeditor5-core/issues/73#issuecomment-311602619.

So, we need to figure out the right solution and as this issues is not annoying or something (the editor doesn't blow up) this can be postponed. I guess that at some point we'll simply implement the ability to link images.

**Comment by oleq** [comment]
> So, we need to figure out the right solution and as this issues is not annoying or something (the editor doesn't blow up) this can be postponed. I guess that at some point we'll simply implement the ability to link images.

I wonder if the issue may re–appear in other features (also in the future). Essentially the case is that some inline attribute can be applied in such situation
```
ab<element><child>[c]</child></element>de
```

but cannot be applied to the `element` as a whole in

```
ab[<element><child>c</child></element>]de
```

It might be a very common case in different kind of widgets, e.g. if we ever decided blockquote should be one, etc.. We might need to figure out the solution anyway then.

**Comment by Reinmar** [comment]
I'm not sure what you mean. The other cases which I mentioned are bold and italic. They are a slightly different case than link, but the effect is identical – if you apply bold to a selected image that bold applies in the caption. While it's hard to tell whether this makes sense with an image, that would certainly be the expected result if blockquote was some kind of widget.

The editor will work in these cases as long as schema is well defined. However, it's a UX question whether people want to apply inline styles to block widgets at all. And which of these inline styles should rather apply to the whole element (like we want the link to do).

**Comment by Reinmar** [comment]
I'm not sure why we kept this issue open. The only one which makes sense now is: https://github.com/ckeditor/ckeditor5/issues/702 (allow linking images).
