### ISSUE TITLE
Listen on the Tab key with a lower priority

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#87]
See https://github.com/ckeditor/ckeditor5-list/issues/43.

**Comment by Reinmar** [comment]
I've just realised that to do that, we'd need to improve `KeystrokeHandler` cause it doesn't support priorities now.

**Comment by oleq** [comment]
The following syntax
```js
keystrokes.set( 'CTRL+A', callback, { priority: 'high' } );
```
should do the trick. There are some issues, though:
1. List will probably use [`editor.keystrokes`](https://github.com/ckeditor/ckeditor5-core/blob/master/src/editor/standardeditor.js#L49) while `LinkFormView` uses [own KH](https://github.com/ckeditor/ckeditor5-link/blob/master/src/ui/linkformview.js#L53) to [enable focus cycling](https://github.com/ckeditor/ckeditor5-link/blob/master/src/ui/linkformview.js#L100-L111). How to implement priorities across 2 different KH instances, in different features, which attach their own [DOM listeners](https://github.com/ckeditor/ckeditor5-utils/blob/master/src/keystrokehandler.js#L55-L57)?
   * I remember when we first implemented `KeystrokeHandler` and `EditingKeystrokeHandler` we discussed the possibility that we might need to propagate the keystroke information (it's core system) between UI components at some point. Perhaps we've just reached this point in this issue?
2. How to implement priorities in the KH itself, which attaches a single  [DOM listener](https://github.com/ckeditor/ckeditor5-utils/blob/master/src/keystrokehandler.js#L55-L57) for all keystrokes? We would need a more complex data structure to store the information about the keystrokes to know which has greater priority than the other (also considering the order or `KH.set()`). Can we trade off some of the performance for simplicity and attach a new DOM listener with given priority for each single keystroke and let `Emitter` handle priorities?

**Comment by Reinmar** [comment]
> How to implement priorities in the KH itself, which attaches a single DOM listener for all keystrokes?

Well... I've got no idea :D No idea at all... It seems that everything would need to register their own listeners or that everything would need to use the keystroke handler. The former seems more reasonable.

**Comment by Reinmar** [comment]
One more idea... In fact, it was mentioned somewhere in the past – the keystroke handler could not have `add()` method, but fire events called `key:Ctrl+a` or something.

**Comment by Reinmar** [comment]
But... it doesn't actually help much... still, all its listeners will need to be copied to the targets on which it's listening.

**Comment by oleq** [comment]
I'm afraid we might need to propagate focus across the (UI) code base in a similar way we deal with locales... We could pass `env = { locale: ..., keystrokes: ... }` object to the each constructor instead of locale.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5-link/issues/146.
